# Generated by Django 4.0.5 on 2022-07-03 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_books_book_img_alter_books_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='fathername',
            new_name='father_name',
        ),
    ]
