# Generated by Django 4.0.5 on 2022-07-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rename_fathername_author_father_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_img',
            field=models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d/', verbose_name='Ссылка на изображение'),
        ),
    ]
