# Generated by Django 4.0.6 on 2022-07-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_books_book_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.ManyToManyField(related_name='books', to='books.author', verbose_name='Авторы'),
        ),
    ]
