# Generated by Django 4.0.5 on 2022-07-24 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_books_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='id_publishing_house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publishinghouse_books', to='books.publishinghouse', verbose_name='Издательство'),
        ),
    ]
