# Generated by Django 4.0.5 on 2022-07-24 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('librarys', '0003_librarys_library_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarys',
            name='id_librarys_storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='librarysstorage_librarys', to='librarys.librarysstorage', verbose_name='Хранилище библиотеки'),
        ),
    ]
